import type { Metadata } from 'next'
import {  Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import  Providers  from '@/context/provider'

const poppins = Poppins({
  weight: '700',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Spring-Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
       <Providers>
       <Navbar/>
       
        {children}
       </Providers>
        </body>
    </html>
  )
}
